apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lqx9v8dcq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lqx9v8dcq-python 
  name: lqx9v8dcq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lqx9v8dcq-python 
